### ISSUE TITLE
To-Do tasklist 📋

### ISSUE THREAD

**Issue by soofg** [MichaelChorak/matching-app#1]
# **My To Do's** 

> A overview of my tasks 😋

- [x] Make Wireframes (profile, filtering, dishes, favorites/save)
- [x] Finish my part of the styling
- [x] Connect to a database
- [x] Make collection with some dishes in database
- [x] Make a icon for matching-app
- [x] Make filtering work
- [x] Make favorite/save dish work
- [x] Research topic Minify
- [x] Start trying to minify code
- [x] Try to regularly push my commits to GitHub
- [x] Fix my code in a new branch tp push to main 

_Changes can / will be made in the future :)_   
_Let me know what you all think!_

**Comment by MichaelChorak** [comment]
Looks good, if you need any help with these to-do's u can hit me up!
